/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPackingRouteImport } from './routes/_app/packing'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as AppTripsIndexRouteImport } from './routes/_app/trips.index'
import { Route as AppTripsNewRouteImport } from './routes/_app/trips.new'
import { Route as AppTripsTripIdRouteImport } from './routes/_app/trips.$tripId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPackingRoute = AppPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsIndexRoute = AppTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities': typeof AppActivitiesRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/journal': typeof AppJournalRoute
  '/packing': typeof AppPackingRoute
  '/settings': typeof AppSettingsRoute
  '/share/$slug': typeof ShareSlugRoute
  '/trips/$tripId': typeof AppTripsTripIdRoute
  '/trips/new': typeof AppTripsNewRoute
  '/trips/': typeof AppTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities': typeof AppActivitiesRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/journal': typeof AppJournalRoute
  '/packing': typeof AppPackingRoute
  '/settings': typeof AppSettingsRoute
  '/share/$slug': typeof ShareSlugRoute
  '/trips/$tripId': typeof AppTripsTripIdRoute
  '/trips/new': typeof AppTripsNewRoute
  '/trips': typeof AppTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/packing': typeof AppPackingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_app/trips/$tripId': typeof AppTripsTripIdRoute
  '/_app/trips/new': typeof AppTripsNewRoute
  '/_app/trips/': typeof AppTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/activities'
    | '/admin'
    | '/ai'
    | '/budget'
    | '/dashboard'
    | '/discover'
    | '/journal'
    | '/packing'
    | '/settings'
    | '/share/$slug'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/activities'
    | '/admin'
    | '/ai'
    | '/budget'
    | '/dashboard'
    | '/discover'
    | '/journal'
    | '/packing'
    | '/settings'
    | '/share/$slug'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/activities'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/budget'
    | '/_app/dashboard'
    | '/_app/discover'
    | '/_app/journal'
    | '/_app/packing'
    | '/_app/settings'
    | '/share/$slug'
    | '/_app/trips/$tripId'
    | '/_app/trips/new'
    | '/_app/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ShareSlugRoute: typeof ShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packing': {
      id: '/_app/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof AppPackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/': {
      id: '/_app/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AppTripsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/$tripId': {
      id: '/_app/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppJournalRoute: typeof AppJournalRoute
  AppPackingRoute: typeof AppPackingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTripsTripIdRoute: typeof AppTripsTripIdRoute
  AppTripsNewRoute: typeof AppTripsNewRoute
  AppTripsIndexRoute: typeof AppTripsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppJournalRoute: AppJournalRoute,
  AppPackingRoute: AppPackingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTripsTripIdRoute: AppTripsTripIdRoute,
  AppTripsNewRoute: AppTripsNewRoute,
  AppTripsIndexRoute: AppTripsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ShareSlugRoute: ShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
