# Generated by Django 6.0.5 on 2026-05-10 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('cost_index', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('adventure', 'Adventure'), ('culture', 'Culture'), ('nightlife', 'Nightlife')], max_length=30)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared', 'Shared')], default='private', max_length=20)),
                ('cover_photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('documents', 'Documents'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=30)),
                ('is_packed', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='core.trip')),
            ],
            options={
                'ordering': ['is_packed', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='core.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.trip')),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TripNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.tripstop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StopActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('estimated_cost_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_instances', to='core.activity')),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_activities', to='core.tripstop')),
            ],
        ),
    ]
